FROM almalinux:9
ENV course="devops"\
    trainer="siva"\
    learner="bharathi"
#RUN echo "hello ${trainer}" > /tmp/devops.txt
ARG USERNAME=siva
RUN echo "hello user: ${USERNAME}"
CMD ["sleep","500"]

